/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    blog: Blog;
    realisations: Realisation;
    temoignages: Temoignage;
    equipe: Equipe;
    faq: Faq;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    blog: BlogSelect<false> | BlogSelect<true>;
    realisations: RealisationsSelect<false> | RealisationsSelect<true>;
    temoignages: TemoignagesSelect<false> | TemoignagesSelect<true>;
    equipe: EquipeSelect<false> | EquipeSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'service-images': ServiceImage;
    parametres: Parametre;
  };
  globalsSelect: {
    'service-images': ServiceImagesSelect<false> | ServiceImagesSelect<true>;
    parametres: ParametresSelect<false> | ParametresSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Créez, modifiez et illustrez vos articles de blog.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  titre: string;
  /**
   * Laissez vide : il se remplit tout seul à partir du titre.
   */
  slug?: string | null;
  categorie?: ('branding' | 'marketing-digital' | 'ia' | 'carte-digitale' | 'agence') | null;
  date?: string | null;
  image?: (number | null) | Media;
  extrait?: string | null;
  tempsLecture?: number | null;
  auteur?: string | null;
  aLaUne?: boolean | null;
  /**
   * Ex : communication-visuelle
   */
  serviceLie?: string | null;
  landingLiee?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Toutes les images téléversées (couvertures, illustrations…).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Décrivez l’image en une phrase (ex. « Séance photo corporate dans nos locaux »).
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    vignette?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    carte?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    grande?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Le portfolio : une fiche par projet, publiée quand elle est prête.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realisations".
 */
export interface Realisation {
  id: number;
  titre: string;
  /**
   * Laissez vide : il se remplit tout seul à partir du titre.
   */
  slug?: string | null;
  /**
   * Décochée : la fiche reste invisible des visiteurs.
   */
  publiee?: boolean | null;
  /**
   * Du plus petit au plus grand.
   */
  ordre?: number | null;
  client: string;
  /**
   * Ex. 2026
   */
  annee: string;
  /**
   * Le premier choisi donne le type de mission affiché.
   */
  services: ('visuel' | 'digital' | 'marketing' | 'ia' | 'photo-video')[];
  secteur: 'btp' | 'distribution' | 'immobilier' | 'sante' | 'institution' | 'services';
  extrait: string;
  visuel?: (number | null) | Media;
  galerie?: (number | Media)[] | null;
  contexte: string;
  objectifs?:
    | {
        texte: string;
        id?: string | null;
      }[]
    | null;
  reponse: string;
  resultats?:
    | {
        /**
         * Ex. « +40 % »
         */
        valeur: string;
        /**
         * Ex. « de demandes entrantes »
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  temoignage?: {
    verbatim?: string | null;
    nom?: string | null;
    fonction?: string | null;
  };
  /**
   * Facultatif : deux images de même cadrage, le visiteur déplace un curseur.
   */
  avantApres?: {
    activer?: boolean | null;
    avant?: (number | null) | Media;
    apres?: (number | null) | Media;
  };
  /**
   * Mise en avant comme étude de cas détaillée.
   */
  etudeDeCas?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les témoignages clients affichés sur la page d’accueil.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "temoignages".
 */
export interface Temoignage {
  id: number;
  nom: string;
  fonction: string;
  entreprise: string;
  verbatim: string;
  /**
   * Un témoignage ne se publie pas sans accord écrit du client, conservé par l’agence.
   */
  consentement: boolean;
  /**
   * Du plus petit au plus grand.
   */
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les portraits affichés sur la page À propos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipe".
 */
export interface Equipe {
  id: number;
  nom: string;
  role: string;
  photo?: (number | null) | Media;
  /**
   * Facultatif. Adresse complète du profil.
   */
  linkedin?: string | null;
  /**
   * Du plus petit au plus grand.
   */
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les questions-réponses de la page FAQ, par thème.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  theme: 'agence' | 'tarifs' | 'pros-cards' | 'support';
  question: string;
  reponse: string;
  /**
   * Dans le thème, du plus petit au plus grand.
   */
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les personnes autorisées à se connecter au tableau de bord.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'administrateur' | 'editeur';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'blog';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'realisations';
        value: number | Realisation;
      } | null)
    | ({
        relationTo: 'temoignages';
        value: number | Temoignage;
      } | null)
    | ({
        relationTo: 'equipe';
        value: number | Equipe;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  titre?: T;
  slug?: T;
  categorie?: T;
  date?: T;
  image?: T;
  extrait?: T;
  tempsLecture?: T;
  auteur?: T;
  aLaUne?: T;
  serviceLie?: T;
  landingLiee?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realisations_select".
 */
export interface RealisationsSelect<T extends boolean = true> {
  titre?: T;
  slug?: T;
  publiee?: T;
  ordre?: T;
  client?: T;
  annee?: T;
  services?: T;
  secteur?: T;
  extrait?: T;
  visuel?: T;
  galerie?: T;
  contexte?: T;
  objectifs?:
    | T
    | {
        texte?: T;
        id?: T;
      };
  reponse?: T;
  resultats?:
    | T
    | {
        valeur?: T;
        label?: T;
        id?: T;
      };
  temoignage?:
    | T
    | {
        verbatim?: T;
        nom?: T;
        fonction?: T;
      };
  avantApres?:
    | T
    | {
        activer?: T;
        avant?: T;
        apres?: T;
      };
  etudeDeCas?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "temoignages_select".
 */
export interface TemoignagesSelect<T extends boolean = true> {
  nom?: T;
  fonction?: T;
  entreprise?: T;
  verbatim?: T;
  consentement?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipe_select".
 */
export interface EquipeSelect<T extends boolean = true> {
  nom?: T;
  role?: T;
  photo?: T;
  linkedin?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  theme?: T;
  question?: T;
  reponse?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        vignette?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        carte?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        grande?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Illustrations de chaque bloc des pages Services.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-images".
 */
export interface ServiceImage {
  id: number;
  'communication-visuelle'?: {
    img1?: (number | null) | Media;
    img2?: (number | null) | Media;
    img3?: (number | null) | Media;
  };
  'communication-digitale'?: {
    img1?: (number | null) | Media;
    img2?: (number | null) | Media;
    img3?: (number | null) | Media;
  };
  'marketing-strategie'?: {
    img1?: (number | null) | Media;
    img2?: (number | null) | Media;
    img3?: (number | null) | Media;
  };
  'automatisation-ia'?: {
    img1?: (number | null) | Media;
    img2?: (number | null) | Media;
    img3?: (number | null) | Media;
  };
  'photo-video'?: {
    img1?: (number | null) | Media;
    img2?: (number | null) | Media;
    img3?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Coordonnées, réseaux sociaux, liens PROS.CARDS et mentions légales.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parametres".
 */
export interface Parametre {
  id: number;
  nom: string;
  /**
   * Sous le logo, dans le pied de page et les partages.
   */
  baseline: string;
  telephone: string;
  telephoneFixe?: string | null;
  /**
   * Format international sans « + » ni espace, ex. 2250700000000.
   */
  whatsapp: string;
  email: string;
  adresse: string;
  ville: string;
  pays: string;
  /**
   * Ex. « Lundi–vendredi, 8 h–18 h ». Vide : non affiché.
   */
  horaires?: string | null;
  delaiReponse?: string | null;
  /**
   * Adresse Cal.com ou Calendly. Vide : le bouton « Prendre rendez-vous » mène à la page Contact.
   */
  rdvUrl?: string | null;
  /**
   * Un réseau sans adresse n’est pas affiché.
   */
  reseaux?: {
    linkedin?: string | null;
    instagram?: string | null;
    facebook?: string | null;
  };
  /**
   * Points d’entrée vers la plateforme. Un lien vide mène à la page Contact.
   */
  prosCards?: {
    inscription?: string | null;
    connexion?: string | null;
    demo?: string | null;
  };
  rccm?: string | null;
  directeurPublication?: string | null;
  hebergeur?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-images_select".
 */
export interface ServiceImagesSelect<T extends boolean = true> {
  'communication-visuelle'?:
    | T
    | {
        img1?: T;
        img2?: T;
        img3?: T;
      };
  'communication-digitale'?:
    | T
    | {
        img1?: T;
        img2?: T;
        img3?: T;
      };
  'marketing-strategie'?:
    | T
    | {
        img1?: T;
        img2?: T;
        img3?: T;
      };
  'automatisation-ia'?:
    | T
    | {
        img1?: T;
        img2?: T;
        img3?: T;
      };
  'photo-video'?:
    | T
    | {
        img1?: T;
        img2?: T;
        img3?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parametres_select".
 */
export interface ParametresSelect<T extends boolean = true> {
  nom?: T;
  baseline?: T;
  telephone?: T;
  telephoneFixe?: T;
  whatsapp?: T;
  email?: T;
  adresse?: T;
  ville?: T;
  pays?: T;
  horaires?: T;
  delaiReponse?: T;
  rdvUrl?: T;
  reseaux?:
    | T
    | {
        linkedin?: T;
        instagram?: T;
        facebook?: T;
      };
  prosCards?:
    | T
    | {
        inscription?: T;
        connexion?: T;
        demo?: T;
      };
  rccm?: T;
  directeurPublication?: T;
  hebergeur?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}